title: AdminFaces 
description: Integrating Primefaces, Bootstrap and Admin LTE into your JSF application.
google_analytics:
url: https://adminfaces.github.io
baseurl: /admin-showcase/
repository: adminfaces/admin-showcase

markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/adminfaces

