title: AdminFaces 
description: Integrating Primefaces, Bootstrap and Admin LTE into your JSF application.
google_analytics:
url: https://adminfaces.github.io
baseurl: /site
repository: adminfaces/admin-showcase
markdown: kramdown
highlighter: rouge
include: ['_pages']
permalink: pretty
gems:      [jekyll-paginate]
excerpt_separator: "\n\n"

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  
  
coderay:
  coderay_wrap:              div
  coderay_line_numbers:      inline
  coderay_line_number_start: 1
  coderay_tab_width:         4
  coderay_bold_every:        10
  coderay_css:               style  
# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #


exclude:
  - vendor/
  - README.adoc
  
disqus:
  shortname: 'adminfaces'  
  
social:
  - title: github
    url: https://github.com/adminfaces
  - title: twitter
    url: https://twitter.com/admin_faces/  
    
# Outputting
permalink:     /:title.html
paginate: 10
paginate_path: /page:num
timezone:      null

