title: AdminFaces 
description: Integrating Primefaces, Bootstrap and Admin LTE into your JSF application.
google_analytics:
url: https://adminfaces.github.io
baseurl: /site
repository: adminfaces/admin-showcase
markdown: kramdown
include: ['_pages']
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/adminfaces

